# -*- coding: utf-8 -*-
"""DevikaTPlifesigth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f9NVB7CqT5ho2zKgIwBYSSbVn2FFzeAo
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.float_format', lambda x: f'{x:,.2f}')
print('Libraries loaded.')

# Option A: Upload the xlsx file to Colab (simplest for now)
from google.colab import files
print('Please upload Northfield_Co_Case_Study.xlsx')
uploaded = files.upload()
fname = list(uploaded.keys())[0]

df = pd.read_excel(fname, sheet_name='Master data')
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date').reset_index(drop=True)

# Derived date columns used throughout
df['year']    = df['Date'].dt.year
df['month']   = df['Date'].dt.to_period('M').astype(str)
df['dow']     = df['Date'].dt.day_name()
df['dow_num'] = df['Date'].dt.dayofweek

print(f'Loaded: {df.shape[0]} rows, {df.shape[1]} columns')
df.head(3)

# Coverage & missing values
print(f'Date range: {df.Date.min().date()} to {df.Date.max().date()}')
print(f'Days covered: {(df.Date.max() - df.Date.min()).days + 1}   Rows: {len(df)}   Duplicates: {df.Date.duplicated().sum()}')
missing = df.isna().sum()
print(f'\nColumns with missing values: {(missing > 0).sum()}')
if (missing > 0).any():
    print(missing[missing > 0])
else:
    print('No missing values across all 23 columns.')

# Roll-up integrity check
google_components = ['spend_Google_Branded','spend_Google_Non_Branded','spend_Google_PMAX',
                     'spend_Google_Demand_Gen','spend_Google_Others']
meta_components   = ['spend_Meta_ASC','spend_Meta_Retargeting','spend_Meta_Prospecting']

g_diff = (df['spend_Google'] - df[google_components].sum(axis=1)).abs()
m_diff = (df['spend_Meta']   - df[meta_components].sum(axis=1)).abs()

print(f'\nGoogle roll-up vs components — mean abs diff: ${g_diff.mean():.4f}, max: ${g_diff.max():.4f}')
print(f'Meta   roll-up vs components — mean abs diff: ${m_diff.mean():.4f}, max: ${m_diff.max():.4f}')
print('=> Roll-ups match components. We use components only in analysis; never sum roll-ups + components.')

flags = ['Promotion_Discount','Offline_Promo','UWG_Mailing','holiday_list','BFCM_Promo_Effect']
print('DAY-TYPE FLAGS  (share of 852 days where flag = 1)')
for f in flags:
    print(f'  {f:22s}  {df[f].mean()*100:5.1f}%   ({df[f].sum():>3.0f} days)')

print('\nKPI SUMMARY  (USD)')
print(df[['Total_Revenue','Revenue_New_Customer']].describe().round(0).to_string())

total_rev = df['Total_Revenue'].sum()
new_rev   = df['Revenue_New_Customer'].sum()
avg_daily = df['Total_Revenue'].mean()
spend_cols = ['spend_Google','spend_Meta','microsoft_spend','criteo_spend','cost_outbrain',
              'Awin_spend','influencer_spend']
total_media = df[spend_cols].sum().sum()

print(f'\n  TOTAL REVENUE          ${total_rev/1e6:6.2f} M')
print(f'  AVG DAILY REVENUE      ${avg_daily/1e3:6.1f} K')
print(f'  NEW-CUSTOMER REVENUE   ${new_rev/1e6:6.2f} M  ({new_rev/total_rev*100:.1f}% of total)')
print(f'  TOTAL PAID MEDIA       ${total_media/1e6:6.2f} M  ({total_media/total_rev*100:.1f}% of revenue)')

fig = go.Figure()
fig.add_trace(go.Scatter(x=df['Date'], y=df['Total_Revenue'],
    mode='lines', name='Total Revenue', line=dict(color='#1f3a68', width=1.2),
    hovertemplate='%{x|%b %d, %Y}<br>Revenue: $%{y:,.0f}<extra></extra>'))
fig.add_trace(go.Scatter(x=df['Date'], y=df['Revenue_New_Customer'],
    mode='lines', name='New-Customer Revenue', line=dict(color='#c47f2a', width=1),
    hovertemplate='%{x|%b %d, %Y}<br>New-cust: $%{y:,.0f}<extra></extra>'))

# Shade BFCM windows
bfcm_days = df[df['BFCM_Promo_Effect']==1]['Date']
for year, block in bfcm_days.groupby(bfcm_days.dt.year):
    fig.add_vrect(x0=block.min(), x1=block.max(),
                  fillcolor='rgba(220,60,60,0.10)', line_width=0,
                  annotation_text=f'BFCM {year}', annotation_position='top left',
                  annotation_font_size=10)

# Mark mailing days
mail_days = df[df['UWG_Mailing']==1]
fig.add_trace(go.Scatter(x=mail_days['Date'], y=mail_days['Total_Revenue'],
    mode='markers', name='UWG Mailing day',
    marker=dict(color='#2a8a3e', size=6, symbol='diamond'),
    hovertemplate='Mailing on %{x|%b %d, %Y}<br>Revenue: $%{y:,.0f}<extra></extra>'))

fig.update_layout(
    title='Daily online revenue — BFCM peaks and mailing spikes are the story',
    xaxis_title='Date', yaxis_title='USD', height=480, hovermode='x unified',
    legend=dict(orientation='h', y=-0.15))
fig.show()

monthly = df.groupby([df['Date'].dt.year.rename('Year'),
                      df['Date'].dt.month.rename('Month')])['Total_Revenue'].sum().reset_index()
monthly['MonthName'] = pd.to_datetime(monthly['Month'], format='%m').dt.strftime('%b')

fig = px.bar(monthly, x='MonthName', y='Total_Revenue', color='Year', barmode='group',
             category_orders={'MonthName':['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']},
             color_discrete_sequence=['#1f3a68','#c47f2a','#2a8a3e'],
             title='Monthly revenue by year — November is the peak, Jan/Feb the trough')
fig.update_layout(height=420, yaxis_title='Revenue (USD)', xaxis_title=None)
fig.show()

dow_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
by_dow = df.groupby('dow')['Total_Revenue'].mean().reindex(dow_order).reset_index()

fig = px.bar(by_dow, x='dow', y='Total_Revenue',
             color='Total_Revenue', color_continuous_scale='Blues',
             title='Average daily revenue by weekday')
fig.update_layout(height=350, yaxis_title='Avg revenue (USD)', xaxis_title=None,
                  coloraxis_showscale=False)
fig.show()

def lift_row(flag):
    on  = df[df[flag]==1]['Total_Revenue']
    off = df[df[flag]==0]['Total_Revenue']
    return {'Flag': flag, 'Days ON': len(on),
            'Avg rev ON ($)':  round(on.mean()),
            'Avg rev OFF ($)': round(off.mean()),
            'Lift %': round((on.mean()/off.mean()-1)*100, 1)}

flag_list = ['Promotion_Discount','UWG_Mailing','BFCM_Promo_Effect','Offline_Promo','holiday_list']
lift = pd.DataFrame([lift_row(f) for f in flag_list]).sort_values('Lift %', ascending=False)
print('CONDITIONAL LIFT — mean revenue on flag=1 days vs flag=0 days')
print(lift.to_string(index=False))

fig = px.bar(lift, x='Flag', y='Lift %', color='Lift %',
             color_continuous_scale=['#a8c3e6','#1f3a68','#0a1d3a'],
             title='Revenue lift on flag-ON days vs flag-OFF days')
fig.update_traces(text=lift['Lift %'].astype(str)+'%', textposition='outside')
fig.update_layout(height=400, coloraxis_showscale=False, xaxis_title=None)
fig.show()

fig = go.Figure()
for is_promo, name, color in [(0,'Full-price day','#c47f2a'), (1,'Promotion day','#1f3a68')]:
    fig.add_trace(go.Box(y=df[df['Promotion_Discount']==is_promo]['Total_Revenue'],
                         name=name, marker_color=color, boxmean=True))
fig.update_layout(
    title='Revenue distribution — promo vs full-price days<br><sub>Promo is 67% of days: it is the norm, not the exception</sub>',
    yaxis_title='Total revenue (USD)', height=420, showlegend=False)
fig.show()

mail_nonbfcm = df[(df['UWG_Mailing']==1) & (df['BFCM_Promo_Effect']==0)]['Total_Revenue']
non_nonbfcm  = df[(df['UWG_Mailing']==0) & (df['BFCM_Promo_Effect']==0)]['Total_Revenue']

print('UWG MAILING LIFT — excluding BFCM window')
print(f'  Mailing days (non-BFCM):     n = {len(mail_nonbfcm)},  avg = ${mail_nonbfcm.mean():,.0f}')
print(f'  Non-mailing days (non-BFCM): n = {len(non_nonbfcm)}, avg = ${non_nonbfcm.mean():,.0f}')
print(f'  Adjusted lift: +{(mail_nonbfcm.mean()/non_nonbfcm.mean()-1)*100:.1f}%')
print('\n=> Even after removing BFCM, mailing days ~2x the revenue of non-mailing days.')

bfcm_years = sorted(df[df['BFCM_Promo_Effect']==1]['Date'].dt.year.unique())

fig = go.Figure()
for y in bfcm_years:
    year_df = df[(df['Date'].dt.year==y) & (df['Date'].dt.month.isin([11,12]))]
    fig.add_trace(go.Scatter(x=year_df['Date'].dt.strftime('%b %d'),
                             y=year_df['Total_Revenue'],
                             mode='lines+markers', name=f'{y}',
                             hovertemplate='%{x}<br>$%{y:,.0f}<extra></extra>'))
fig.update_layout(title='Nov–Dec revenue by year — BFCM week is the biggest revenue event',
                  height=400, yaxis_title='Revenue (USD)', xaxis_title=None)
fig.show()

channels = {
    'Google Branded':      'spend_Google_Branded',
    'Google Non-Branded':  'spend_Google_Non_Branded',
    'Google PMAX':         'spend_Google_PMAX',
    'Google Demand Gen':   'spend_Google_Demand_Gen',
    'Google Others':       'spend_Google_Others',
    'Meta ASC':            'spend_Meta_ASC',
    'Meta Retargeting':    'spend_Meta_Retargeting',
    'Meta Prospecting':    'spend_Meta_Prospecting',
    'Microsoft Ads':       'microsoft_spend',
    'Criteo':              'criteo_spend',
    'Outbrain':            'cost_outbrain',
    'Awin (affiliate)':    'Awin_spend',
    'Influencer':          'influencer_spend',
}
mix = pd.DataFrame({
    'Channel': list(channels.keys()),
    'Total Spend': [df[c].sum() for c in channels.values()]
}).sort_values('Total Spend', ascending=True)
mix['% of paid media'] = mix['Total Spend'] / mix['Total Spend'].sum() * 100

fig = px.bar(mix, x='Total Spend', y='Channel', orientation='h',
             text=mix['% of paid media'].round(1).astype(str)+'%',
             color='Total Spend', color_continuous_scale='Blues',
             title='Total paid-media spend by channel (Apr 2024 – Jul 2026)')
fig.update_layout(height=520, coloraxis_showscale=False, yaxis_title=None)
fig.update_traces(textposition='outside')
fig.show()

spend_cols_comp = list(channels.values())
monthly_spend = df.groupby(df['Date'].dt.to_period('M').astype(str))[spend_cols_comp].sum().reset_index()
monthly_spend = monthly_spend.rename(columns={monthly_spend.columns[0]:'Month'})
monthly_long = monthly_spend.melt(id_vars='Month', value_vars=spend_cols_comp,
                                  var_name='Channel', value_name='Spend')
monthly_long['Channel'] = monthly_long['Channel'].map({v:k for k,v in channels.items()})

fig = px.area(monthly_long, x='Month', y='Spend', color='Channel',
              title='Monthly paid-media mix over time',
              color_discrete_sequence=px.colors.qualitative.Set2)
fig.update_layout(height=460, xaxis_title=None, yaxis_title='Monthly spend (USD)')
fig.show()

non_bfcm = df[df['BFCM_Promo_Effect']==0]
harvest = []
for name, col in channels.items():
    m  = non_bfcm[non_bfcm['UWG_Mailing']==1][col].mean()
    nm = non_bfcm[non_bfcm['UWG_Mailing']==0][col].mean()
    if nm > 0:
        harvest.append({'Channel': name,
                        'Mailing day avg ($)': round(m),
                        'Non-mailing avg ($)': round(nm),
                        'Uplift %': round((m/nm-1)*100, 1)})
harvest = pd.DataFrame(harvest).sort_values('Uplift %', ascending=False)
print('CHANNEL SPEND ON MAILING DAYS vs NON-MAILING DAYS  (excluding BFCM)')
print(harvest.to_string(index=False))

fig = px.bar(harvest.sort_values('Uplift %'), x='Uplift %', y='Channel', orientation='h',
             color='Uplift %',
             color_continuous_scale=[[0,'#4a7ab8'],[0.5,'#e6c15b'],[1,'#c73e3e']],
             title='How much each channel scales UP on mailing days<br>' +
                   '<sub>Awin nearly doubles — classic demand-harvesting signature</sub>')
fig.update_traces(text=harvest.sort_values('Uplift %')['Uplift %'].astype(str)+'%',
                  textposition='outside')
fig.update_layout(height=520, coloraxis_showscale=False, yaxis_title=None)
fig.show()

corr_rows = []
for name, col in channels.items():
    r = df[col].corr(df['Total_Revenue'])
    corr_rows.append({'Channel': name, 'Correlation with revenue': round(r, 3)})
corr_df = pd.DataFrame(corr_rows).sort_values('Correlation with revenue', ascending=True)

fig = px.bar(corr_df, x='Correlation with revenue', y='Channel', orientation='h',
             color='Correlation with revenue', color_continuous_scale='RdBu_r',
             range_color=[-0.2, 0.8],
             title='Correlation of daily channel spend with daily revenue<br>' +
                   '<sub>High correlation ≠ causation</sub>')
fig.update_layout(height=520, yaxis_title=None)
fig.show()

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Scatter(x=df['Date'], y=df['Total_Revenue'].rolling(7).mean(),
                         name='Total revenue (7-day avg)',
                         line=dict(color='#1f3a68', width=1.5)),
              secondary_y=False)
fig.add_trace(go.Scatter(x=df['Date'], y=df['Awin_spend'].rolling(7).mean(),
                         name='Awin spend (7-day avg)',
                         line=dict(color='#c73e3e', width=1.5)),
              secondary_y=True)
fig.update_layout(title='Revenue and Awin spend move together — every revenue peak has a matching Awin peak',
                  height=420, hovermode='x unified')
fig.update_yaxes(title_text='Revenue ($)', secondary_y=False)
fig.update_yaxes(title_text='Awin spend ($)', secondary_y=True)
fig.show()

def nc_share(subset):
    return subset['Revenue_New_Customer'].sum() / subset['Total_Revenue'].sum() * 100

print('NEW-CUSTOMER SHARE OF REVENUE — by day type')
print(f"  Overall:              {nc_share(df):.1f}%")
print(f"  Promo days:           {nc_share(df[df['Promotion_Discount']==1]):.1f}%")
print(f"  Full-price days:      {nc_share(df[df['Promotion_Discount']==0]):.1f}%")
print(f"  Mailing days:         {nc_share(df[df['UWG_Mailing']==1]):.1f}%")
print(f"  Non-mailing days:     {nc_share(df[df['UWG_Mailing']==0]):.1f}%")
print(f"  BFCM days:            {nc_share(df[df['BFCM_Promo_Effect']==1]):.1f}%")

monthly_prospect = df.groupby(df['Date'].dt.to_period('M').astype(str)).agg(
    prospect_spend=('spend_Meta_Prospecting','sum'),
    new_cust_rev=('Revenue_New_Customer','sum')
).reset_index()
monthly_prospect.columns = ['Month','prospect_spend','new_cust_rev']

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Bar(x=monthly_prospect['Month'], y=monthly_prospect['prospect_spend'],
                     name='Meta Prospecting spend', marker_color='#c47f2a', opacity=0.65),
              secondary_y=False)
fig.add_trace(go.Scatter(x=monthly_prospect['Month'], y=monthly_prospect['new_cust_rev'],
                         name='New-customer revenue', mode='lines+markers',
                         line=dict(color='#1f3a68', width=2)),
              secondary_y=True)
fig.update_layout(title='Meta Prospecting spend vs new-customer revenue',
                  height=420, hovermode='x unified')
fig.update_yaxes(title_text='Prospecting spend ($)', secondary_y=False)
fig.update_yaxes(title_text='New-customer revenue ($)', secondary_y=True)
fig.show()

print("""
════════════════════════════════════════════════════════
  KEY FINDINGS
════════════════════════════════════════════════════════

1. MAILINGS are the biggest revenue lever
   → Mailing days: $116K avg vs $57K non-mailing (+105%)
   → Even excluding BFCM the lift is ~2x

2. PROMOTIONS are Northfield's default state
   → Site-wide discounts on 67% of all 852 days
   → Promo days avg $68K vs $50K full-price (+36%)

3. BFCM is the single biggest revenue event
   → 17 BFCM days avg $171K vs $60K other days (+185%)

4. PAID MEDIA is only 8% of revenue
   → Brand runs on organic + CRM + promo calendar

5. BRAND SEARCH & AWIN show demand-harvesting pattern
   → On mailing days: Awin +94%, Google Branded +16%
   → Awin r=0.76 with revenue is co-movement, not causation

6. FULL-PRICE days over-index for new customers
   → 36% new-cust share vs 31% on promo days
   → Promos may be reactivating existing customers

════════════════════════════════════════════════════════
  RECOMMENDATIONS
════════════════════════════════════════════════════════

1. AUDIT Awin + Google Branded for incrementality
   → Geo hold-out on Awin (2-4 weeks)
   → Brand-bidding pause test on Google Branded
   → Reallocate freed budget to prospecting

2. TEST increased UWG mailing cadence
   → Currently 9% of days; test 12-15%
   → Monitor unsubscribe / open-rate fatigue

3. DECOUPLE prospecting from promo calendar
   → Full-price days deliver more new customers by share
   → Keep prospecting spend stable on non-promo days

════════════════════════════════════════════════════════
  NEXT INVESTIGATIONS
════════════════════════════════════════════════════════
- Media-mix model (MMM) for causal decomposition
- Cohort LTV by acquisition day-type
- Fatigue analysis before mailing cadence increase
- Awin attribution-window audit
""")

!pip install streamlit pyngrok pandas plotly openpyxl -q
print("✅ Installed")

from google.colab import files
import os
os.makedirs('data', exist_ok=True)
print("📁 Upload Northfield_Co_Case_Study.xlsx now:")
uploaded = files.upload()
for fname in uploaded.keys():
    os.rename(fname, f'data/{fname}')
print(f"✅ Moved to data/{list(uploaded.keys())[0]}")

app_code = r'''
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

st.set_page_config(page_title="Northfield & Co. Dashboard", page_icon="📊", layout="wide")

st.markdown("""
<style>
    .main .block-container { padding-top: 2rem; padding-bottom: 2rem; }
    h1 { color: #1f3a68; }
    h2 { color: #1f3a68; border-bottom: 2px solid #e0e6ed; padding-bottom: 0.3rem; }
    [data-testid="stMetricValue"] { font-size: 1.8rem; color: #1f3a68; }
    [data-testid="stMetricLabel"] { font-size: 0.85rem; }
</style>
""", unsafe_allow_html=True)

@st.cache_data
def load_data():
    df = pd.read_excel('data/Northfield_Co_Case_Study.xlsx', sheet_name='Master data')
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date').reset_index(drop=True)
    df['year']  = df['Date'].dt.year
    df['month'] = df['Date'].dt.to_period('M').astype(str)
    df['dow']   = df['Date'].dt.day_name()
    return df

try:
    df = load_data()
except FileNotFoundError:
    st.error("Data file missing")
    st.stop()

CHANNELS = {
    'Google Branded':'spend_Google_Branded','Google Non-Branded':'spend_Google_Non_Branded',
    'Google PMAX':'spend_Google_PMAX','Google Demand Gen':'spend_Google_Demand_Gen',
    'Google Others':'spend_Google_Others','Meta ASC':'spend_Meta_ASC',
    'Meta Retargeting':'spend_Meta_Retargeting','Meta Prospecting':'spend_Meta_Prospecting',
    'Microsoft Ads':'microsoft_spend','Criteo':'criteo_spend','Outbrain':'cost_outbrain',
    'Awin (affiliate)':'Awin_spend','Influencer':'influencer_spend',
}
SPEND_COLS = list(CHANNELS.values())

st.sidebar.title("📊 Northfield & Co.")
st.sidebar.markdown("**US e-commerce dashboard**")
st.sidebar.markdown("*Devika T P · Case study*")
st.sidebar.markdown("---")
page = st.sidebar.radio("**Navigate**",
    ["🏠 Overview","🎯 Promotions & Mailings","📢 Marketing Mix",
     "🔍 Incrementality","👥 New Customers","💡 Findings & Recommendations"])
st.sidebar.markdown("---")
date_min = df['Date'].min().date()
date_max = df['Date'].max().date()
date_range = st.sidebar.date_input("Date range", value=(date_min, date_max),
                                    min_value=date_min, max_value=date_max)
if len(date_range) == 2:
    dff = df[(df['Date'].dt.date >= date_range[0]) & (df['Date'].dt.date <= date_range[1])]
else:
    dff = df
st.sidebar.caption(f"📅 {len(dff)} days in view")

def big_kpis(data):
    c1, c2, c3, c4 = st.columns(4)
    total_rev   = data['Total_Revenue'].sum()
    avg_daily   = data['Total_Revenue'].mean()
    new_rev     = data['Revenue_New_Customer'].sum()
    new_share   = new_rev/total_rev*100 if total_rev else 0
    total_media = data[SPEND_COLS].sum().sum()
    media_pct   = total_media/total_rev*100 if total_rev else 0
    c1.metric("💰 Total Revenue", f"${total_rev/1e6:.2f}M")
    c2.metric("📆 Avg Daily Revenue", f"${avg_daily/1e3:.1f}K")
    c3.metric("🆕 New-Customer Revenue", f"${new_rev/1e6:.2f}M", f"{new_share:.1f}% of total")
    c4.metric("📢 Paid Media", f"${total_media/1e6:.2f}M", f"{media_pct:.1f}% of revenue")

if page == "🏠 Overview":
    st.title("Northfield & Co. — Business Overview")
    st.markdown("*US e-commerce daily data · 1 Apr 2024 – 31 Jul 2026*")
    big_kpis(dff)
    st.markdown("---")
    st.subheader("Daily online revenue over time")
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=dff['Date'], y=dff['Total_Revenue'], mode='lines',
                             name='Total Revenue', line=dict(color='#1f3a68', width=1.3)))
    fig.add_trace(go.Scatter(x=dff['Date'], y=dff['Revenue_New_Customer'], mode='lines',
                             name='New-Customer Revenue', line=dict(color='#c47f2a', width=1)))
    bfcm_days = dff[dff['BFCM_Promo_Effect']==1]['Date']
    for year, block in bfcm_days.groupby(bfcm_days.dt.year):
        fig.add_vrect(x0=block.min(), x1=block.max(),
                      fillcolor='rgba(220,60,60,0.12)', line_width=0,
                      annotation_text=f'BFCM {year}', annotation_position='top left')
    mail_days = dff[dff['UWG_Mailing']==1]
    fig.add_trace(go.Scatter(x=mail_days['Date'], y=mail_days['Total_Revenue'], mode='markers',
                             name='UWG Mailing', marker=dict(color='#2a8a3e', size=7, symbol='diamond')))
    fig.update_layout(height=440, hovermode='x unified', yaxis_title='USD',
                      legend=dict(orientation='h', y=-0.15))
    st.plotly_chart(fig, use_container_width=True)
    st.info("**Read:** BFCM (red shaded) hold biggest peaks. Green diamonds = mailing days — consistently above baseline.")
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Monthly revenue by year")
        monthly = dff.groupby([dff['Date'].dt.year.rename('Year'),
                               dff['Date'].dt.month.rename('Month')])['Total_Revenue'].sum().reset_index()
        monthly['MonthName'] = pd.to_datetime(monthly['Month'], format='%m').dt.strftime('%b')
        fig = px.bar(monthly, x='MonthName', y='Total_Revenue', color='Year', barmode='group',
                     category_orders={'MonthName':['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']},
                     color_discrete_sequence=['#1f3a68','#c47f2a','#2a8a3e'])
        fig.update_layout(height=340, yaxis_title='Revenue (USD)')
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        st.subheader("Average revenue by weekday")
        dow_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
        by_dow = dff.groupby('dow')['Total_Revenue'].mean().reindex(dow_order).reset_index()
        fig = px.bar(by_dow, x='dow', y='Total_Revenue', color='Total_Revenue', color_continuous_scale='Blues')
        fig.update_layout(height=340, yaxis_title='Avg revenue (USD)', coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

elif page == "🎯 Promotions & Mailings":
    st.title("Promotions & Mailings — What drives daily revenue")
    st.caption("Conditional averages, not causal estimates.")
    big_kpis(dff)
    st.markdown("---")
    def lift_row(flag):
        on  = dff[dff[flag]==1]['Total_Revenue']
        off = dff[dff[flag]==0]['Total_Revenue']
        return {'Flag': flag, 'Days ON': len(on),
                'Avg rev ON ($)':  round(on.mean()) if len(on) else 0,
                'Avg rev OFF ($)': round(off.mean()) if len(off) else 0,
                'Lift %': round((on.mean()/off.mean()-1)*100, 1) if len(on) and len(off) and off.mean()>0 else 0}
    flag_list = ['Promotion_Discount','UWG_Mailing','BFCM_Promo_Effect','Offline_Promo','holiday_list']
    lift = pd.DataFrame([lift_row(f) for f in flag_list]).sort_values('Lift %', ascending=False)
    st.subheader("Revenue lift on flag-ON vs flag-OFF days")
    col1, col2 = st.columns([2, 1])
    with col1:
        fig = px.bar(lift, x='Flag', y='Lift %', color='Lift %',
                     color_continuous_scale=['#a8c3e6','#1f3a68','#0a1d3a'])
        fig.update_traces(text=lift['Lift %'].astype(str)+'%', textposition='outside')
        fig.update_layout(height=380, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        st.dataframe(lift, use_container_width=True, hide_index=True)
    st.markdown("---")
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Promo vs full-price distribution")
        fig = go.Figure()
        for is_promo, name, color in [(0,'Full-price','#c47f2a'), (1,'Promotion','#1f3a68')]:
            fig.add_trace(go.Box(y=dff[dff['Promotion_Discount']==is_promo]['Total_Revenue'],
                                 name=name, marker_color=color, boxmean=True))
        fig.update_layout(height=380, yaxis_title='Revenue (USD)', showlegend=False)
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        st.subheader("Mailing lift (excl. BFCM)")
        non_bfcm = dff[dff['BFCM_Promo_Effect']==0]
        mail_avg = non_bfcm[non_bfcm['UWG_Mailing']==1]['Total_Revenue'].mean()
        nomail_avg = non_bfcm[non_bfcm['UWG_Mailing']==0]['Total_Revenue'].mean()
        adjusted_lift = (mail_avg/nomail_avg-1)*100 if nomail_avg else 0
        m1, m2, m3 = st.columns(3)
        m1.metric("Mailing", f"${mail_avg/1e3:.0f}K")
        m2.metric("Non-mailing", f"${nomail_avg/1e3:.0f}K")
        m3.metric("Lift", f"+{adjusted_lift:.0f}%")
        st.success(f"**~2× revenue on mailing days** — biggest lever in the data.")
    st.markdown("---")
    st.subheader("Nov–Dec revenue by year")
    bfcm_years = sorted(dff[dff['BFCM_Promo_Effect']==1]['Date'].dt.year.unique())
    fig = go.Figure()
    for y in bfcm_years:
        year_df = dff[(dff['Date'].dt.year==y) & (dff['Date'].dt.month.isin([11,12]))]
        fig.add_trace(go.Scatter(x=year_df['Date'].dt.strftime('%b %d'), y=year_df['Total_Revenue'],
                                 mode='lines+markers', name=f'{y}'))
    fig.update_layout(height=380, yaxis_title='Revenue (USD)')
    st.plotly_chart(fig, use_container_width=True)

elif page == "📢 Marketing Mix":
    st.title("Marketing Mix — Where the ad money goes")
    big_kpis(dff)
    st.markdown("---")
    mix = pd.DataFrame({'Channel': list(CHANNELS.keys()),
                        'Total Spend': [dff[c].sum() for c in CHANNELS.values()]}).sort_values('Total Spend', ascending=True)
    mix['% of paid media'] = mix['Total Spend'] / mix['Total Spend'].sum() * 100
    col1, col2 = st.columns([2, 1])
    with col1:
        st.subheader("Total spend by channel")
        fig = px.bar(mix, x='Total Spend', y='Channel', orientation='h',
                     text=mix['% of paid media'].round(1).astype(str)+'%',
                     color='Total Spend', color_continuous_scale='Blues')
        fig.update_layout(height=520, coloraxis_showscale=False)
        fig.update_traces(textposition='outside')
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        st.subheader("Top 3 channels")
        top3 = mix.sort_values('Total Spend', ascending=False).head(3)
        for _, r in top3.iterrows():
            st.metric(r['Channel'], f"${r['Total Spend']/1e6:.2f}M", f"{r['% of paid media']:.1f}%")
    st.markdown("---")
    st.subheader("Monthly media mix")
    monthly_spend = dff.groupby(dff['Date'].dt.to_period('M').astype(str))[SPEND_COLS].sum().reset_index()
    monthly_spend = monthly_spend.rename(columns={monthly_spend.columns[0]:'Month'})
    monthly_long = monthly_spend.melt(id_vars='Month', value_vars=SPEND_COLS,
                                      var_name='Channel', value_name='Spend')
    monthly_long['Channel'] = monthly_long['Channel'].map({v:k for k,v in CHANNELS.items()})
    fig = px.area(monthly_long, x='Month', y='Spend', color='Channel',
                  color_discrete_sequence=px.colors.qualitative.Set2)
    fig.update_layout(height=420, yaxis_title='Monthly spend (USD)')
    st.plotly_chart(fig, use_container_width=True)
    st.subheader("Media efficiency over time")
    monthly_kpi = dff.groupby(dff['Date'].dt.to_period('M').astype(str)).apply(
        lambda g: pd.Series({'revenue': g['Total_Revenue'].sum(), 'media': g[SPEND_COLS].sum().sum()})
    ).reset_index()
    monthly_kpi.columns = ['Month','revenue','media']
    monthly_kpi['media_pct'] = monthly_kpi['media']/monthly_kpi['revenue']*100
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=monthly_kpi['Month'], y=monthly_kpi['media_pct'], mode='lines+markers',
                             name='Media % of revenue', line=dict(color='#c47f2a', width=2)))
    fig.add_hline(y=monthly_kpi['media_pct'].mean(), line_dash='dash',
                  annotation_text=f"avg {monthly_kpi['media_pct'].mean():.1f}%", line_color='gray')
    fig.update_layout(height=360, yaxis_title='%')
    st.plotly_chart(fig, use_container_width=True)
    st.info(f"**~{monthly_kpi['media_pct'].mean():.0f}% of revenue** — stable, low-intensity mass-brand mix.")

elif page == "🔍 Incrementality":
    st.title("The Incrementality Question")
    st.markdown('> *"Are brand-search and affiliate lines capturing demand created elsewhere?"* — Marketing team')
    st.markdown("Brand search & Awin sit at the END of the buying journey. If they spike when mailings/promos run, they may just be **taking credit for revenue the CRM already created**.")
    st.markdown("---")
    non_bfcm = dff[dff['BFCM_Promo_Effect']==0]
    harvest = []
    for name, col in CHANNELS.items():
        m  = non_bfcm[non_bfcm['UWG_Mailing']==1][col].mean()
        nm = non_bfcm[non_bfcm['UWG_Mailing']==0][col].mean()
        if nm > 0:
            harvest.append({'Channel': name, 'Mailing avg ($)': round(m),
                            'Non-mailing avg ($)': round(nm), 'Uplift %': round((m/nm-1)*100, 1)})
    harvest = pd.DataFrame(harvest).sort_values('Uplift %', ascending=False)
    st.subheader("How much each channel scales UP on mailing days")
    col1, col2 = st.columns([2, 1])
    with col1:
        fig = px.bar(harvest.sort_values('Uplift %'), x='Uplift %', y='Channel', orientation='h',
                     color='Uplift %', color_continuous_scale=[[0,'#4a7ab8'],[0.5,'#e6c15b'],[1,'#c73e3e']])
        fig.update_traces(text=harvest.sort_values('Uplift %')['Uplift %'].astype(str)+'%', textposition='outside')
        fig.update_layout(height=500, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        st.dataframe(harvest, use_container_width=True, hide_index=True, height=500)
    st.error("**🚨 Smoking gun.** Awin +94%, Google Branded +16% on mailing days — demand-harvesting pattern.")
    st.markdown("---")
    st.subheader("Awin spend and revenue move together")
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_trace(go.Scatter(x=dff['Date'], y=dff['Total_Revenue'].rolling(7).mean(),
                             name='Revenue (7d avg)', line=dict(color='#1f3a68', width=1.5)), secondary_y=False)
    fig.add_trace(go.Scatter(x=dff['Date'], y=dff['Awin_spend'].rolling(7).mean(),
                             name='Awin spend (7d avg)', line=dict(color='#c73e3e', width=1.5)), secondary_y=True)
    fig.update_layout(height=380, hovermode='x unified')
    fig.update_yaxes(title_text='Revenue ($)', secondary_y=False)
    fig.update_yaxes(title_text='Awin spend ($)', secondary_y=True)
    st.plotly_chart(fig, use_container_width=True)
    st.subheader("Correlation of channel spend with revenue")
    corr_rows = [{'Channel': name, 'Correlation': round(dff[col].corr(dff['Total_Revenue']), 3)}
                 for name, col in CHANNELS.items()]
    corr_df = pd.DataFrame(corr_rows).sort_values('Correlation', ascending=True)
    fig = px.bar(corr_df, x='Correlation', y='Channel', orientation='h',
                 color='Correlation', color_continuous_scale='RdBu_r', range_color=[-0.2, 0.8])
    fig.update_layout(height=460)
    st.plotly_chart(fig, use_container_width=True)
    st.warning("**High correlation ≠ causation.** Awin's 0.76 is co-movement — both rise on mailing days.")

elif page == "👥 New Customers":
    st.title("New-Customer Acquisition")
    big_kpis(dff)
    st.markdown("---")
    def nc_share(subset):
        r = subset['Total_Revenue'].sum()
        return subset['Revenue_New_Customer'].sum() / r * 100 if r else 0
    st.subheader("New-customer share of revenue — by day type")
    shares = pd.DataFrame([
        {'Day type':'Overall',         'NC share %': round(nc_share(dff), 1)},
        {'Day type':'Promo days',      'NC share %': round(nc_share(dff[dff['Promotion_Discount']==1]), 1)},
        {'Day type':'Full-price days', 'NC share %': round(nc_share(dff[dff['Promotion_Discount']==0]), 1)},
        {'Day type':'Mailing days',    'NC share %': round(nc_share(dff[dff['UWG_Mailing']==1]), 1)},
        {'Day type':'Non-mailing days','NC share %': round(nc_share(dff[dff['UWG_Mailing']==0]), 1)},
        {'Day type':'BFCM days',       'NC share %': round(nc_share(dff[dff['BFCM_Promo_Effect']==1]), 1)},
    ])
    col1, col2 = st.columns([2, 1])
    with col1:
        fig = px.bar(shares, x='Day type', y='NC share %', color='NC share %',
                     color_continuous_scale='Oranges')
        fig.update_traces(text=shares['NC share %'].astype(str)+'%', textposition='outside')
        fig.update_layout(height=400, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        st.dataframe(shares, use_container_width=True, hide_index=True)
    st.warning("**Full-price days deliver higher NC share (36% vs 31%)** — promos may reactivate existing customers, not acquire new ones.")
    st.markdown("---")
    st.subheader("Meta Prospecting spend vs new-customer revenue")
    monthly_prospect = dff.groupby(dff['Date'].dt.to_period('M').astype(str)).agg(
        prospect_spend=('spend_Meta_Prospecting','sum'),
        new_cust_rev=('Revenue_New_Customer','sum')).reset_index()
    monthly_prospect.columns = ['Month','prospect_spend','new_cust_rev']
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_trace(go.Bar(x=monthly_prospect['Month'], y=monthly_prospect['prospect_spend'],
                         name='Meta Prospecting', marker_color='#c47f2a', opacity=0.65), secondary_y=False)
    fig.add_trace(go.Scatter(x=monthly_prospect['Month'], y=monthly_prospect['new_cust_rev'],
                             name='New-cust revenue', mode='lines+markers',
                             line=dict(color='#1f3a68', width=2)), secondary_y=True)
    fig.update_layout(height=420, hovermode='x unified')
    st.plotly_chart(fig, use_container_width=True)

elif page == "💡 Findings & Recommendations":
    st.title("Findings & Recommendations")
    st.header("🔑 Key findings")
    findings = [
        ("1. Mailings — biggest revenue lever", "Mailing days: ~$116K vs ~$57K (+105%). ~2× even excluding BFCM. Only 9% of days."),
        ("2. Promotion is the default", "67% of days have discounts. Promo days: $68K vs $50K (+36%)."),
        ("3. BFCM = biggest event", "17 BFCM days avg $171K vs $60K (+185%). Two BFCMs explain the peaks."),
        ("4. Paid media is only 8% of revenue", "CRM + promotional calendar + organic run this brand."),
        ("5. Brand search & Awin harvest demand", "Awin +94%, Google Branded +16% on mailing days. r=0.76 is co-movement, not causation."),
        ("6. Full-price days over-index for new customers", "36% vs 31% NC share. Promos may reactivate existing customers."),
    ]
    for title, body in findings:
        st.markdown(f"##### {title}")
        st.markdown(body)
        st.markdown("")
    st.markdown("---")
    st.header("💼 Recommendations")
    st.markdown("""
    ##### 1. Audit Awin & Google Branded for incrementality
    2–4 week geo hold-out on Awin, brand-bidding pause on Google Branded. Reallocate to prospecting.

    ##### 2. Test higher UWG mailing cadence
    Currently 9% of days. Test 12–15% with fatigue monitoring.

    ##### 3. Decouple prospecting from promo calendar
    Keep prospecting stable on non-promo days.
    """)
    st.markdown("---")
    st.header("🔬 Next investigations")
    st.markdown("""
    - Media-mix model (MMM)
    - Cohort LTV by acquisition day-type
    - UWG fatigue analysis
    - Awin attribution-window audit
    """)
    st.markdown("---")
    st.caption("*Devika T P · MSc Statistics · CHRIST (Deemed to be University), Bengaluru*")
'''

with open('app.py', 'w') as f:
    f.write(app_code)
print(f"✅ Wrote app.py ({len(app_code)} chars)")

from google.colab import files
uploaded = files.upload()

import pandas as pd
import json

# Load your data (make sure Northfield_Co_Case_Study.xlsx is uploaded to Colab)
df = pd.read_excel('Northfield_Co_Case_Study.xlsx', sheet_name='Master data')
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date').reset_index(drop=True)

# Add season column
def get_season(m):
    if m in [3,4,5]: return 'Spring'
    if m in [6,7,8]: return 'Summer'
    if m in [9,10]: return 'Fall'
    if m in [11,12]: return 'Holiday'
    return 'Winter'

df['season'] = df['Date'].dt.month.apply(get_season)
df['dow'] = df['Date'].dt.day_name()
df['date_str'] = df['Date'].dt.strftime('%Y-%m-%d')

# Prepare compact JSON for JavaScript
cols = ['date_str','Total_Revenue','Revenue_New_Customer',
        'UWG_Mailing','BFCM_Promo_Effect','holiday_list','Offline_Promo','Promotion_Discount',
        'spend_Google_Branded','spend_Google_Non_Branded','spend_Google_PMAX',
        'spend_Google_Demand_Gen','spend_Google_Others',
        'spend_Meta_ASC','spend_Meta_Retargeting','spend_Meta_Prospecting',
        'microsoft_spend','criteo_spend','cost_outbrain','Awin_spend','influencer_spend',
        'season','dow']
df_out = df[cols].copy()
df_out.columns = ['Date' if c=='date_str' else c for c in df_out.columns]
for c in df_out.select_dtypes(include='float').columns:
    df_out[c] = df_out[c].round(2)

data_json = df_out.to_json(orient='records')
print(f"✅ Data prepared: {len(df)} rows, {len(data_json)/1024:.1f} KB")

html_top = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Northfield & Co. — Interactive Dashboard</title>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<style>
* { box-sizing: border-box; }
body { margin: 0; font-family: -apple-system, sans-serif; background: #f5f7fa; color: #222; line-height: 1.6; }
.header { background: linear-gradient(135deg, #1f3a68 0%, #2a4d80 100%); color: white; padding: 30px 60px 25px; }
.header h1 { margin: 0; font-size: 2rem; }
.header .subtitle { opacity: 0.85; margin-top: 8px; font-size: 0.95rem; }
.header .author { opacity: 0.7; margin-top: 4px; font-size: 0.85rem; }
.filter-bar { background: white; padding: 18px 60px; border-bottom: 1px solid #e0e6ed; position: sticky; top: 0; z-index: 100; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }
.filter-grid { display: grid; grid-template-columns: 2fr 1fr 1fr auto; gap: 30px; align-items: center; }
.filter-group label { display: block; font-size: 0.75rem; font-weight: 600; color: #666; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px; }
.filter-group select, .filter-group input[type="date"] { padding: 8px 12px; border: 1px solid #ccd; border-radius: 6px; font-size: 0.9rem; background: white; width: 100%; }
.date-range { display: grid; grid-template-columns: 1fr auto 1fr; gap: 8px; align-items: end; }
.date-range span { color: #666; padding-bottom: 10px; }
.filter-reset { padding: 10px 18px; background: #1f3a68; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 0.85rem; font-weight: 500; }
.filter-reset:hover { background: #2a4d80; }
.filter-summary { grid-column: 1 / -1; margin-top: 10px; font-size: 0.85rem; color: #555; padding: 8px 12px; background: #f0f5fb; border-radius: 4px; }
.filter-summary strong { color: #1f3a68; }
.nav { background: #f0f2f5; padding: 10px 60px; border-bottom: 1px solid #e0e6ed; font-size: 0.85rem; }
.nav a { display: inline-block; margin-right: 20px; color: #1f3a68; text-decoration: none; font-weight: 500; }
.nav a:hover { color: #c47f2a; }
.container { max-width: 1400px; margin: 0 auto; padding: 30px 60px; }
.section { margin-bottom: 50px; scroll-margin-top: 180px; }
.section h2 { color: #1f3a68; border-bottom: 3px solid #1f3a68; padding-bottom: 8px; margin-top: 0; }
.kpi-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 20px 0 30px 0; }
.kpi-card { background: white; padding: 18px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); border-left: 4px solid #1f3a68; }
.kpi-label { font-size: 0.75rem; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
.kpi-value { font-size: 1.6rem; color: #1f3a68; font-weight: 600; margin-top: 4px; }
.kpi-sub { font-size: 0.8rem; color: #888; margin-top: 4px; }
.chart-box { background: white; padding: 18px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); margin-bottom: 20px; }
.chart-box h3 { margin: 0 0 10px 0; color: #1f3a68; font-size: 1rem; }
.two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
.callout { background: #e8f0f8; border-left: 4px solid #1f3a68; padding: 14px 18px; margin: 16px 0; border-radius: 4px; font-size: 0.9rem; }
.callout.warning { background: #fff4e5; border-left-color: #c47f2a; }
.callout.danger { background: #fbe9e7; border-left-color: #c73e3e; }
.callout.success { background: #e8f5e9; border-left-color: #2a8a3e; }
.findings-list { list-style: none; padding: 0; }
.findings-list li { background: white; padding: 14px 18px; margin-bottom: 10px; border-radius: 6px; border-left: 4px solid #1f3a68; box-shadow: 0 1px 2px rgba(0,0,0,0.05); font-size: 0.9rem; }
.findings-list li strong { color: #1f3a68; display: block; margin-bottom: 4px; }
table { width: 100%; border-collapse: collapse; margin: 10px 0; background: white; border-radius: 6px; overflow: hidden; font-size: 0.85rem; }
th { background: #1f3a68; color: white; padding: 8px 10px; text-align: left; }
td { padding: 8px 10px; border-bottom: 1px solid #e0e6ed; }
footer { text-align: center; padding: 25px; color: #888; font-size: 0.8rem; border-top: 1px solid #e0e6ed; }
.empty-state { text-align: center; padding: 40px; color: #999; background: white; border-radius: 8px; border: 2px dashed #ddd; }
</style>
</head>
<body>
<div class="header">
<h1>📊 Northfield & Co. — Interactive Dashboard</h1>
<div class="subtitle">US e-commerce daily data · 1 Apr 2024 – 31 Jul 2026 · 852 days</div>
<div class="author">Prepared by Devika T P · MSc Statistics · CHRIST (Deemed to be University), Bengaluru</div>
</div>
<div class="filter-bar">
<div class="filter-grid">
<div class="filter-group"><label>📅 Date Range</label>
<div class="date-range">
<input type="date" id="dateStart" min="2024-04-01" max="2026-07-31" value="2024-04-01">
<span>to</span>
<input type="date" id="dateEnd" min="2024-04-01" max="2026-07-31" value="2026-07-31">
</div></div>
<div class="filter-group"><label>🌦️ Season</label>
<select id="seasonFilter">
<option value="All">All Seasons</option>
<option value="Spring">Spring (Mar–May)</option>
<option value="Summer">Summer (Jun–Aug)</option>
<option value="Fall">Fall (Sep–Oct)</option>
<option value="Holiday">Holiday (Nov–Dec)</option>
<option value="Winter">Winter (Jan–Feb)</option>
</select></div>
<div class="filter-group"><label>🎯 Day Type</label>
<select id="dayTypeFilter">
<option value="All">All Days</option>
<option value="Promo">Promotion days only</option>
<option value="FullPrice">Full-price days only</option>
<option value="Mailing">Mailing days only</option>
<option value="BFCM">BFCM days only</option>
<option value="Holiday">Public holidays only</option>
</select></div>
<button class="filter-reset" onclick="resetFilters()">↺ Reset</button>
<div class="filter-summary" id="filterSummary"></div>
</div></div>
<nav class="nav">
<a href="#overview">🏠 Overview</a>
<a href="#promotions">🎯 Promotions</a>
<a href="#marketing">📢 Marketing Mix</a>
<a href="#incrementality">🔍 Incrementality</a>
<a href="#newcust">👥 New Customers</a>
<a href="#findings">💡 Findings</a>
</nav>
<div class="container">
<div class="section" id="overview">
<h2>Business Overview</h2>
<div class="kpi-row" id="kpiRow"></div>
<div class="chart-box"><h3>Daily online revenue over time</h3><div id="c1"></div></div>
<div class="callout"><strong>Read:</strong> BFCM windows (shaded red) hold the biggest revenue peaks. Green diamonds = mailing days.</div>
<div class="two-col">
<div class="chart-box"><h3>Monthly revenue by year</h3><div id="c2"></div></div>
<div class="chart-box"><h3>Average revenue by weekday</h3><div id="c3"></div></div>
</div></div>
<div class="section" id="promotions">
<h2>Promotions & Mailings</h2>
<p style="color:#666;font-size:0.85rem;">Conditional averages, not causal estimates.</p>
<div class="chart-box"><h3>Revenue lift on flag-ON vs flag-OFF days</h3><div id="c4"></div></div>
<div id="liftTable"></div>
<div class="two-col">
<div class="chart-box"><h3>Promo vs full-price distribution</h3><div id="c5"></div></div>
<div class="chart-box"><h3>Nov–Dec revenue by year</h3><div id="c6"></div></div>
</div>
<div class="callout success"><strong>Key insight:</strong> Mailing days show ~2× revenue vs non-mailing days. Biggest lever.</div>
</div>
<div class="section" id="marketing">
<h2>Marketing Mix</h2>
<div class="chart-box"><h3>Total paid-media spend by channel</h3><div id="c7"></div></div>
<div class="chart-box"><h3>Monthly paid-media mix over time</h3><div id="c8"></div></div>
<div class="chart-box"><h3>Media efficiency over time (% of revenue)</h3><div id="c9"></div></div>
<div class="callout" id="efficiencyCallout"></div>
</div>
<div class="section" id="incrementality">
<h2>🔍 The Incrementality Question</h2>
<blockquote style="font-style:italic;color:#666;border-left:3px solid #ccc;padding-left:16px;">"Are the brand-search and affiliate lines capturing demand created elsewhere?"</blockquote>
<div class="chart-box"><h3>How much each channel scales UP on mailing days (excl. BFCM)</h3><div id="c10"></div></div>
<div class="callout danger"><strong>🚨 Smoking gun.</strong> Awin +94%, Google Branded +16% on mailing days.</div>
<div class="chart-box"><h3>Awin spend and revenue move together</h3><div id="c11"></div></div>
<div class="chart-box"><h3>Correlation of each channel's spend with daily revenue</h3><div id="c12"></div></div>
<div class="callout warning"><strong>High correlation ≠ causation.</strong> Awin's correlation reflects co-movement.</div>
</div>
<div class="section" id="newcust">
<h2>👥 New-Customer Acquisition</h2>
<div class="chart-box"><h3>New-customer share of revenue — by day type</h3><div id="c13"></div></div>
<div class="callout warning"><strong>Counter-intuitive.</strong> Full-price days deliver higher NC share (36% vs 31%).</div>
<div class="chart-box"><h3>Meta Prospecting vs new-customer revenue</h3><div id="c14"></div></div>
</div>
<div class="section" id="findings">
<h2>💡 Findings & Recommendations</h2>
<h3 style="color:#1f3a68;">🔑 Key findings</h3>
<ul class="findings-list">
<li><strong>1. Mailings are the biggest revenue lever</strong>+105% on mailing days. ~2× even excluding BFCM.</li>
<li><strong>2. Promotion is Northfield's default state</strong>67% of days have discounts. +36% lift.</li>
<li><strong>3. BFCM is the biggest revenue event</strong>+185% on the 17 BFCM days.</li>
<li><strong>4. Paid media is only 8% of revenue</strong>CRM + promo calendar run this brand.</li>
<li><strong>5. Brand search & Awin harvest demand</strong>Awin +94%, Branded +16% on mailing days.</li>
<li><strong>6. Full-price days over-index for new customers</strong>36% NC share vs 31% on promo days.</li>
</ul>
<h3 style="color:#1f3a68;margin-top:30px;">💼 Recommendations</h3>
<ul class="findings-list">
<li><strong>1. Audit Awin & Google Branded for incrementality</strong>Geo hold-out on Awin, brand-bidding pause test on Google Branded.</li>
<li><strong>2. Test increasing UWG mailing cadence</strong>From 9% to 12–15% with fatigue monitoring.</li>
<li><strong>3. Decouple prospecting from promo calendar</strong>Keep prospecting stable on non-promo days.</li>
</ul>
</div>
</div>
<footer>Prepared by <strong>Devika T P</strong> · MSc Statistics · CHRIST (Deemed to be University), Bengaluru</footer>
<script>
const RAW_DATA = __DATA_JSON__;
const CHANNELS = {'Google Branded':'spend_Google_Branded','Google Non-Branded':'spend_Google_Non_Branded','Google PMAX':'spend_Google_PMAX','Google Demand Gen':'spend_Google_Demand_Gen','Google Others':'spend_Google_Others','Meta ASC':'spend_Meta_ASC','Meta Retargeting':'spend_Meta_Retargeting','Meta Prospecting':'spend_Meta_Prospecting','Microsoft Ads':'microsoft_spend','Criteo':'criteo_spend','Outbrain':'cost_outbrain','Awin (affiliate)':'Awin_spend','Influencer':'influencer_spend'};
const SPEND_COLS = Object.values(CHANNELS);
function getFilteredData(){const s=document.getElementById('dateStart').value,e=document.getElementById('dateEnd').value,sn=document.getElementById('seasonFilter').value,dt=document.getElementById('dayTypeFilter').value;return RAW_DATA.filter(r=>{if(r.Date<s||r.Date>e)return false;if(sn!=='All'&&r.season!==sn)return false;if(dt==='Promo'&&r.Promotion_Discount!==1)return false;if(dt==='FullPrice'&&r.Promotion_Discount!==0)return false;if(dt==='Mailing'&&r.UWG_Mailing!==1)return false;if(dt==='BFCM'&&r.BFCM_Promo_Effect!==1)return false;if(dt==='Holiday'&&r.holiday_list!==1)return false;return true;});}
function updateFilterSummary(d){const s=document.getElementById('dateStart').value,e=document.getElementById('dateEnd').value,sn=document.getElementById('seasonFilter').value,dt=document.getElementById('dayTypeFilter').value;const p=[`<strong>${d.length}</strong> days in view`,`${s} to ${e}`];if(sn!=='All')p.push(`Season: <strong>${sn}</strong>`);if(dt!=='All')p.push(`Day type: <strong>${dt}</strong>`);document.getElementById('filterSummary').innerHTML=p.join(' · ');}
function resetFilters(){document.getElementById('dateStart').value='2024-04-01';document.getElementById('dateEnd').value='2026-07-31';document.getElementById('seasonFilter').value='All';document.getElementById('dayTypeFilter').value='All';renderAll();}
function sum(d,c){return d.reduce((s,r)=>s+(r[c]||0),0);}
function avg(d,c){return d.length?sum(d,c)/d.length:0;}
function fmt(n,dec=0){return Number(n).toLocaleString('en-US',{maximumFractionDigits:dec,minimumFractionDigits:dec});}
function groupBy(d,fn){const g={};d.forEach(r=>{const k=fn(r);if(!g[k])g[k]=[];g[k].push(r);});return g;}
function rollingMean(a,w){return a.map((_,i)=>{const s=Math.max(0,i-w+1),sl=a.slice(s,i+1);return sl.reduce((x,y)=>x+y,0)/sl.length;});}
function chartEmpty(id,m){document.getElementById(id).innerHTML=`<div class="empty-state">${m}</div>`;}
function renderKPIs(d){const tr=sum(d,'Total_Revenue'),ad=avg(d,'Total_Revenue'),nr=sum(d,'Revenue_New_Customer'),ns=tr?(nr/tr*100):0,tm=SPEND_COLS.reduce((s,c)=>s+sum(d,c),0),mp=tr?(tm/tr*100):0;document.getElementById('kpiRow').innerHTML=`<div class="kpi-card"><div class="kpi-label">💰 Total Revenue</div><div class="kpi-value">$${fmt(tr/1e6,2)}M</div><div class="kpi-sub">${d.length} days</div></div><div class="kpi-card"><div class="kpi-label">📆 Avg Daily Revenue</div><div class="kpi-value">$${fmt(ad/1e3,1)}K</div><div class="kpi-sub">Filtered avg</div></div><div class="kpi-card"><div class="kpi-label">🆕 New-Customer Revenue</div><div class="kpi-value">$${fmt(nr/1e6,2)}M</div><div class="kpi-sub">${fmt(ns,1)}% of total</div></div><div class="kpi-card"><div class="kpi-label">📢 Paid Media</div><div class="kpi-value">$${fmt(tm/1e6,2)}M</div><div class="kpi-sub">${fmt(mp,1)}% of revenue</div></div>`;}
function renderChart1(d){if(!d.length)return chartEmpty('c1','No data');const dates=d.map(r=>r.Date),traces=[{x:dates,y:d.map(r=>r.Total_Revenue),mode:'lines',name:'Total Revenue',line:{color:'#1f3a68',width:1.3}},{x:dates,y:d.map(r=>r.Revenue_New_Customer),mode:'lines',name:'New-Cust Revenue',line:{color:'#c47f2a',width:1}}];const m=d.filter(r=>r.UWG_Mailing===1);if(m.length)traces.push({x:m.map(r=>r.Date),y:m.map(r=>r.Total_Revenue),mode:'markers',name:'Mailing',marker:{color:'#2a8a3e',size:6,symbol:'diamond'}});const shapes=[],bfcm=d.filter(r=>r.BFCM_Promo_Effect===1);if(bfcm.length){const g=groupBy(bfcm,r=>r.Date.substring(0,4));Object.entries(g).forEach(([y,days])=>{shapes.push({type:'rect',xref:'x',yref:'paper',x0:days[0].Date,x1:days[days.length-1].Date,y0:0,y1:1,fillcolor:'rgba(220,60,60,0.12)',line:{width:0}});});}Plotly.newPlot('c1',traces,{height:420,hovermode:'x unified',yaxis:{title:'USD'},legend:{orientation:'h',y:-0.15},shapes:shapes,margin:{t:20,b:40,l:60,r:20}},{responsive:true,displayModeBar:false});}
function renderChart2(d){if(!d.length)return chartEmpty('c2','No data');const bym={};d.forEach(r=>{const k=r.Date.substring(0,7);if(!bym[k])bym[k]={year:r.Date.substring(0,4),month:r.Date.substring(5,7),rev:0};bym[k].rev+=r.Total_Revenue;});const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],years=[...new Set(Object.values(bym).map(r=>r.year))].sort(),colors={'2024':'#1f3a68','2025':'#c47f2a','2026':'#2a8a3e'};const traces=years.map(y=>({x:months,name:y,type:'bar',y:months.map((_,i)=>{const k=`${y}-${String(i+1).padStart(2,'0')}`;return bym[k]?bym[k].rev:null;}),marker:{color:colors[y]||'#888'}}));Plotly.newPlot('c2',traces,{height:320,barmode:'group',yaxis:{title:'Revenue (USD)'},margin:{t:20,b:40,l:60,r:20}},{responsive:true,displayModeBar:false});}
function renderChart3(d){if(!d.length)return chartEmpty('c3','No data');const o=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],bd={};o.forEach(x=>bd[x]=[]);d.forEach(r=>{if(bd[r.dow])bd[r.dow].push(r.Total_Revenue);});const y=o.map(x=>bd[x].length?bd[x].reduce((a,b)=>a+b,0)/bd[x].length:0);Plotly.newPlot('c3',[{x:o,y:y,type:'bar',marker:{color:y,colorscale:'Blues'}}],{height:320,yaxis:{title:'Avg revenue (USD)'},margin:{t:20,b:40,l:60,r:20}},{responsive:true,displayModeBar:false});}
function renderChart4(d){const flags=['Promotion_Discount','UWG_Mailing','BFCM_Promo_Effect','Offline_Promo','holiday_list'];const lifts=flags.map(f=>{const on=d.filter(r=>r[f]===1).map(r=>r.Total_Revenue),off=d.filter(r=>r[f]===0).map(r=>r.Total_Revenue),oa=on.length?on.reduce((a,b)=>a+b,0)/on.length:0,ofa=off.length?off.reduce((a,b)=>a+b,0)/off.length:0,l=(on.length&&off.length&&ofa>0)?((oa/ofa-1)*100):null;return{flag:f,on:on.length,off:off.length,oa,ofa,l};}).filter(r=>r.l!==null).sort((a,b)=>b.l-a.l);if(!lifts.length){chartEmpty('c4','No comparable ON/OFF days in current filter');document.getElementById('liftTable').innerHTML='';return;}Plotly.newPlot('c4',[{x:lifts.map(r=>r.flag),y:lifts.map(r=>r.l.toFixed(1)),type:'bar',text:lifts.map(r=>`+${r.l.toFixed(1)}%`),textposition:'outside',marker:{color:lifts.map(r=>r.l),colorscale:[[0,'#a8c3e6'],[0.5,'#1f3a68'],[1,'#0a1d3a']]}}],{height:340,yaxis:{title:'Lift %'},showlegend:false,margin:{t:20,b:60,l:60,r:20}},{responsive:true,displayModeBar:false});document.getElementById('liftTable').innerHTML=`<table><tr><th>Flag</th><th>Days ON</th><th>Avg ON ($)</th><th>Avg OFF ($)</th><th>Lift %</th></tr>${lifts.map(r=>`<tr><td>${r.flag}</td><td>${r.on}</td><td>$${fmt(r.oa)}</td><td>$${fmt(r.ofa)}</td><td><strong>+${r.l.toFixed(1)}%</strong></td></tr>`).join('')}</table>`;}
function renderChart5(d){if(!d.length)return chartEmpty('c5','No data');const p=d.filter(r=>r.Promotion_Discount===1).map(r=>r.Total_Revenue),f=d.filter(r=>r.Promotion_Discount===0).map(r=>r.Total_Revenue),traces=[];if(f.length)traces.push({y:f,name:'Full-price',type:'box',marker:{color:'#c47f2a'},boxmean:true});if(p.length)traces.push({y:p,name:'Promotion',type:'box',marker:{color:'#1f3a68'},boxmean:true});if(!traces.length)return chartEmpty('c5','No comparable days');Plotly.newPlot('c5',traces,{height:340,yaxis:{title:'Revenue (USD)'},showlegend:false,margin:{t:20,b:40,l:60,r:20}},{responsive:true,displayModeBar:false});}
function renderChart6(d){const nd=d.filter(r=>{const m=parseInt(r.Date.substring(5,7));return m===11||m===12;});if(!nd.length)return chartEmpty('c6','No Nov-Dec days in filter');const by=groupBy(nd,r=>r.Date.substring(0,4));const traces=Object.entries(by).sort().map(([y,days])=>({x:days.map(r=>r.Date.substring(5)),y:days.map(r=>r.Total_Revenue),mode:'lines+markers',name:y}));Plotly.newPlot('c6',traces,{height:340,yaxis:{title:'Revenue (USD)'},margin:{t:20,b:40,l:60,r:20}},{responsive:true,displayModeBar:false});}
function renderChart7(d){if(!d.length)return chartEmpty('c7','No data');const rows=Object.entries(CHANNELS).map(([n,c])=>({n,s:sum(d,c)})).sort((a,b)=>a.s-b.s),t=rows.reduce((x,r)=>x+r.s,0);Plotly.newPlot('c7',[{x:rows.map(r=>r.s),y:rows.map(r=>r.n),type:'bar',orientation:'h',text:rows.map(r=>t?`${(r.s/t*100).toFixed(1)}%`:''),textposition:'outside',marker:{color:rows.map(r=>r.s),colorscale:'Blues'}}],{height:480,xaxis:{title:'Spend (USD)'},margin:{t:20,b:40,l:140,r:60}},{responsive:true,displayModeBar:false});}
function renderChart8(d){if(!d.length)return chartEmpty('c8','No data');const bym={};d.forEach(r=>{const m=r.Date.substring(0,7);if(!bym[m]){bym[m]={};SPEND_COLS.forEach(c=>bym[m][c]=0);}SPEND_COLS.forEach(c=>bym[m][c]+=r[c]||0);});const months=Object.keys(bym).sort(),colors=['#66c2a5','#fc8d62','#8da0cb','#e78ac3','#a6d854','#ffd92f','#e5c494','#b3b3b3','#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e'];const traces=Object.entries(CHANNELS).map(([n,c],i)=>({x:months,y:months.map(m=>bym[m][c]),name:n,stackgroup:'one',mode:'none',fillcolor:colors[i%colors.length]}));Plotly.newPlot('c8',traces,{height:400,yaxis:{title:'Monthly spend (USD)'},margin:{t:20,b:40,l:60,r:20}},{responsive:true,displayModeBar:false});}
function renderChart9(d){if(!d.length)return chartEmpty('c9','No data');const bym={};d.forEach(r=>{const m=r.Date.substring(0,7);if(!bym[m])bym[m]={rev:0,media:0};bym[m].rev+=r.Total_Revenue;SPEND_COLS.forEach(c=>bym[m].media+=r[c]||0);});const months=Object.keys(bym).sort(),pcts=months.map(m=>bym[m].rev?bym[m].media/bym[m].rev*100:0),ap=pcts.reduce((a,b)=>a+b,0)/pcts.length;Plotly.newPlot('c9',[{x:months,y:pcts,mode:'lines+markers',line:{color:'#c47f2a',width:2}}],{height:340,yaxis:{title:'%'},shapes:[{type:'line',xref:'paper',x0:0,x1:1,y0:ap,y1:ap,line:{color:'gray',dash:'dash'}}],annotations:[{xref:'paper',yref:'y',x:0.02,y:ap,text:`avg ${ap.toFixed(1)}%`,showarrow:false,bgcolor:'white'}],margin:{t:20,b:40,l:60,r:20}},{responsive:true,displayModeBar:false});document.getElementById('efficiencyCallout').innerHTML=`<strong>Media efficiency in this window: avg ~${ap.toFixed(0)}% of revenue.</strong> Full dataset: ~8%.`;}
function renderChart10(d){const nb=d.filter(r=>r.BFCM_Promo_Effect===0),m=nb.filter(r=>r.UWG_Mailing===1),nm=nb.filter(r=>r.UWG_Mailing===0);if(!m.length||!nm.length){chartEmpty('c10','No mailing/non-mailing comparison in filter');return;}const rows=Object.entries(CHANNELS).map(([n,c])=>{const a=m.reduce((s,r)=>s+(r[c]||0),0)/m.length,b=nm.reduce((s,r)=>s+(r[c]||0),0)/nm.length;return{n,u:b>0?((a/b-1)*100):null};}).filter(r=>r.u!==null).sort((a,b)=>a.u-b.u);Plotly.newPlot('c10',[{x:rows.map(r=>r.u.toFixed(1)),y:rows.map(r=>r.n),type:'bar',orientation:'h',text:rows.map(r=>`${r.u.toFixed(1)}%`),textposition:'outside',marker:{color:rows.map(r=>r.u),colorscale:[[0,'#4a7ab8'],[0.5,'#e6c15b'],[1,'#c73e3e']]}}],{height:480,xaxis:{title:'Uplift %'},margin:{t:20,b:40,l:140,r:60}},{responsive:true,displayModeBar:false});}
function renderChart11(d){if(d.length<7)return chartEmpty('c11','Need 7+ days');const dates=d.map(r=>r.Date),rs=rollingMean(d.map(r=>r.Total_Revenue),7),as=rollingMean(d.map(r=>r.Awin_spend),7);Plotly.newPlot('c11',[{x:dates,y:rs,name:'Revenue (7d avg)',line:{color:'#1f3a68',width:1.5},yaxis:'y'},{x:dates,y:as,name:'Awin (7d avg)',line:{color:'#c73e3e',width:1.5},yaxis:'y2'}],{height:340,hovermode:'x unified',yaxis:{title:'Revenue ($)'},yaxis2:{title:'Awin ($)',overlaying:'y',side:'right'},margin:{t:20,b:40,l:60,r:60}},{responsive:true,displayModeBar:false});}
function renderChart12(d){if(d.length<5)return chartEmpty('c12','Not enough data');function pc(x,y){const n=x.length,mx=x.reduce((a,b)=>a+b,0)/n,my=y.reduce((a,b)=>a+b,0)/n;let nu=0,dx=0,dy=0;for(let i=0;i<n;i++){nu+=(x[i]-mx)*(y[i]-my);dx+=(x[i]-mx)**2;dy+=(y[i]-my)**2;}return(dx&&dy)?nu/Math.sqrt(dx*dy):0;}const rev=d.map(r=>r.Total_Revenue),rows=Object.entries(CHANNELS).map(([n,c])=>({n,r:pc(d.map(x=>x[c]),rev)})).sort((a,b)=>a.r-b.r);Plotly.newPlot('c12',[{x:rows.map(r=>r.r.toFixed(3)),y:rows.map(r=>r.n),type:'bar',orientation:'h',marker:{color:rows.map(r=>r.r),colorscale:'RdBu',cmin:-0.2,cmax:0.8,reversescale:true}}],{height:440,xaxis:{title:'Correlation',range:[-0.2,0.9]},margin:{t:20,b:40,l:140,r:20}},{responsive:true,displayModeBar:false});}
function renderChart13(d){if(!d.length)return chartEmpty('c13','No data');function ns(s){const r=s.reduce((x,y)=>x+y.Total_Revenue,0);return r?s.reduce((x,y)=>x+y.Revenue_New_Customer,0)/r*100:0;}const g=[{n:'Overall',d:d},{n:'Promo',d:d.filter(r=>r.Promotion_Discount===1)},{n:'Full-price',d:d.filter(r=>r.Promotion_Discount===0)},{n:'Mailing',d:d.filter(r=>r.UWG_Mailing===1)},{n:'Non-mailing',d:d.filter(r=>r.UWG_Mailing===0)},{n:'BFCM',d:d.filter(r=>r.BFCM_Promo_Effect===1)}].filter(x=>x.d.length>0);const s=g.map(x=>ns(x.d));Plotly.newPlot('c13',[{x:g.map(x=>x.n),y:s,type:'bar',text:s.map(x=>`${x.toFixed(1)}%`),textposition:'outside',marker:{color:s,colorscale:'Oranges'}}],{height:360,yaxis:{title:'NC share (%)'},margin:{t:20,b:40,l:60,r:20}},{responsive:true,displayModeBar:false});}
function renderChart14(d){if(!d.length)return chartEmpty('c14','No data');const bym={};d.forEach(r=>{const m=r.Date.substring(0,7);if(!bym[m])bym[m]={p:0,n:0};bym[m].p+=r.spend_Meta_Prospecting||0;bym[m].n+=r.Revenue_New_Customer||0;});const months=Object.keys(bym).sort();Plotly.newPlot('c14',[{x:months,y:months.map(m=>bym[m].p),name:'Prospecting',type:'bar',marker:{color:'#c47f2a',opacity:0.65},yaxis:'y'},{x:months,y:months.map(m=>bym[m].n),name:'New-cust rev',mode:'lines+markers',line:{color:'#1f3a68',width:2},yaxis:'y2'}],{height:360,hovermode:'x unified',yaxis:{title:'Prospecting ($)'},yaxis2:{title:'NC rev ($)',overlaying:'y',side:'right'},margin:{t:20,b:40,l:60,r:60}},{responsive:true,displayModeBar:false});}
function renderAll(){const d=getFilteredData();updateFilterSummary(d);renderKPIs(d);renderChart1(d);renderChart2(d);renderChart3(d);renderChart4(d);renderChart5(d);renderChart6(d);renderChart7(d);renderChart8(d);renderChart9(d);renderChart10(d);renderChart11(d);renderChart12(d);renderChart13(d);renderChart14(d);}
['dateStart','dateEnd','seasonFilter','dayTypeFilter'].forEach(id=>{document.getElementById(id).addEventListener('change',renderAll);});
renderAll();
</script>
</body>
</html>
"""

# Inject the data JSON
final_html = html_top.replace('__DATA_JSON__', data_json)

# Save it
with open('northfield_dashboard.html', 'w', encoding='utf-8') as f:
    f.write(final_html)

import os
print(f"✅ Interactive dashboard saved: {os.path.getsize('northfield_dashboard.html')/1024:.1f} KB")

from IPython.display import IFrame, HTML
import base64

with open('northfield_dashboard.html', 'rb') as f:
    html_bytes = f.read()

# Encode as base64 and display in iframe
b64 = base64.b64encode(html_bytes).decode()
display(HTML(f'<iframe src="data:text/html;base64,{b64}" width="100%" height="900" style="border:1px solid #ccc;border-radius:8px;"></iframe>'))

from google.colab import files
files.download('northfield_dashboard.html')

